package com.xivdaily.app.ui.viewmodel

data class SettingsUiState(
    val defaultCategory: String = "cs.CV",
    val customTags: List<String> = emptyList(),
    val defaultDays: Int = 3,
    val themeMode: String = "light",
    val hasSeenOnboarding: Boolean = false,
    val displayName: String = "XivDaily Reader",
    val avatarPreset: String = "study",
    val avatarImageUri: String? = null,
    val language: String = "zh-CN",
    val zoteroConfigured: Boolean = false,
    val zoteroUserId: String? = null,
    val zoteroLibraryType: String? = null,
    val zoteroApiKeyMasked: String? = null,
    val zoteroTargetCollectionName: String = "XivDaily",
    val zoteroTargetCollectionKey: String? = null,
    val zoteroTargetCollectionStatus: String = "not_configured",
    val llmConfigured: Boolean = false,
    val llmBaseUrl: String = "https://yangyioryy.cc.cd",
    val llmModel: String = "glm5",
    val llmApiKeyMasked: String? = null,
    val integrationStatusFailed: Boolean = false,
    val isConfigBusy: Boolean = false,
    val zoteroUserIdDraft: String = "",
    val zoteroLibraryTypeDraft: String = "user",
    val zoteroApiKeyDraft: String = "",
    val zoteroTargetCollectionNameDraft: String = "XivDaily",
    val llmBaseUrlDraft: String = "https://yangyioryy.cc.cd",
    val llmApiKeyDraft: String = "",
    val llmModelDraft: String = "glm5",
    val isThemePickerVisible: Boolean = false,
    val isLanguagePickerVisible: Boolean = false,
    val isZoteroDetailDialogVisible: Boolean = false,
    val isLlmDetailDialogVisible: Boolean = false,
    val isAboutDialogVisible: Boolean = false,
    val isUpdateDialogVisible: Boolean = false,
    val isProfileDialogVisible: Boolean = false,
    val isProfileEditorVisible: Boolean = false,
    val isClearCacheDialogVisible: Boolean = false,
    val cacheStatusText: String = "待清理",
    val actionMessage: String? = null,
    val errorMessage: String? = null,
) {
    val defaultCategoryOptions: List<String>
        get() = (listOf("cs.CV", "cs.LG", "cs.AI", "cs.CL") + customTags).distinct()
}
