package com.xivdaily.app.ui.viewmodel

data class SettingsUiState(
    val defaultCategory: String = "cs.CV",
    val defaultDays: Int = 3,
    val themeMode: String = "system",
    val language: String = "zh-CN",
    val zoteroConfigured: Boolean = false,
    val zoteroUserId: String? = null,
    val zoteroLibraryType: String? = null,
    val zoteroTargetCollectionName: String = "XivDaily",
    val zoteroTargetCollectionKey: String? = null,
    val zoteroTargetCollectionStatus: String = "not_configured",
    val llmConfigured: Boolean = false,
    val integrationStatusFailed: Boolean = false,
    val isThemePickerVisible: Boolean = false,
    val isLanguagePickerVisible: Boolean = false,
    val isZoteroDetailDialogVisible: Boolean = false,
    val isLlmDetailDialogVisible: Boolean = false,
    val isAboutDialogVisible: Boolean = false,
    val isUpdateDialogVisible: Boolean = false,
    val isProfileDialogVisible: Boolean = false,
    val isClearCacheDialogVisible: Boolean = false,
    val cacheStatusText: String = "待清理",
    val actionMessage: String? = null,
    val errorMessage: String? = null,
)
